apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bucket-list
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: bucket-list
      port:
        number: 80
