apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-list-sa
---
# INTENTIONAL MISCONFIGURATION: app has cluster-wide admin privileges
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bucket-list-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bucket-list-sa
    namespace: default
